#{{ if not .Values.disableLogserviceLogservice }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logservice
  namespace: "{{ .Values.nsPrefix }}-logservice"
spec:
  selector:
    matchLabels:
      app: logservice
  template:
    metadata:
       labels:
        app: logservice
       name: logservice
    spec:
      containers:
      - image: {{ .Values.image.logservice }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: logservice
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: logservice-eteshare
          mountPath: /share
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: logservice-eteshare
          hostPath:
            path: /dockerdata-nfs/{{ .Values.nsPrefix }}/logservice/eteshare
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
