apiVersion: v1
kind: Service
metadata:
  labels:
    app: logdemo
  name: logdemo
  namespace: "{{ .Values.nsPrefix }}-logdemo"
spec:
  ports:
  - port: 8080
    nodePort: {{ .Values.nodePortPrefix }}99
  selector:
    app: logdemo
  type: NodePort
